### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by simonw** [simonw/scrape-san-mateo-fire-dispatch#2]
https://github.com/simonw/scrape-san-mateo-fire-dispatch/actions/runs/2869016353
```
Traceback (most recent call last):
  File "/home/runner/work/scrape-san-mateo-fire-dispatch/scrape-san-mateo-fire-dispatch/scrape.py", line 57, in <module>
    html, events = scrape_page(url)
  File "/home/runner/work/scrape-san-mateo-fire-dispatch/scrape-san-mateo-fire-dispatch/scrape.py", line 25, in scrape_page
    summary = tds[1].text.strip()
```

**Comment by simonw** [comment]
Code: https://github.com/simonw/scrape-san-mateo-fire-dispatch/blob/388d8435199b65264df071e8f733067eb30ee845/scrape.py#L21-L27
